apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: postgres-service
    app: demo-vote-app
spec:
  ports:
    - port: 5432 
      targetPort: 5432
  selector:
    name: postgresapp-pod
    app: demo-vote-app