apiVersion: v1
kind: Pod
metadata: 
   name: redisapp-pod
   labels:
      name: redisapp-pod
      app: demo-vote-app
spec:
   containers:
      - name: redis
        image: redis
        ports:
         - containerPort: 6379