apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-service
    app: demo-vote-app
spec:
  ports:
    - port: 6379 
      targetPort: 6379
  selector:
    name: redisapp-pod
    app: demo-vote-app