apiVersion: v1
kind: Service
metadata:
  name: resultapp-service
  labels:
    name: result-service
    app: demo-vote-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005
  selector:
      name: resultapp-pod
      app: demo-vote-app