apiVersion: v1
kind: Pod
metadata: 
   name: resultapp-pod
   labels:
      name: resultapp-pod
      app: demo-vote-app
spec:
   containers:
      - name: result-app
        image: kodekloud/examplevotingapp_vote:v1
        ports:
         - containerPort: 80